### ISSUE TITLE
puppeteer Real Browser Proxy Issue

### ISSUE THREAD

**Issue by EgglezosK** [zfcsoftware/youtube_lessons_resources#2]
Your code works really well, when we are not using proxies. When we are add proxies details the page load until the captcha and freeze there. 

Trying to figure out with this issue but not luck at all. Have you tested with proxies? 

Thanks

**Comment by EgglezosK** [comment]
After some research understand how the code is works! The issue was for some reason on variable " stat " that always was 0. So i change a little bit the check statement. 

`

var checkStat = await page.evaluate(() => {
                var stat = 0;
                var html = "";
                var pageTitle = "";

                if (document.querySelector('html')) {
                    html = document.querySelector('html').innerHTML;
                }

                if (document.title) {
                    pageTitle = document.title.toLowerCase();
                }

                // Check for the specific HTML content or page title
                if (
                    html.indexOf('challenges.cloudflare.com/turnstile') > -1 ||
                    pageTitle.indexOf('just a moment...') > -1
                ) {
                    stat = 1;
                } else {
                    stat = 0; // Change this if you want a different value for other cases
                }

                return stat;
            });

`

**Comment by mdervisaygan** [comment]
@EgglezosK 
Hello, the reason why this code sometimes does not work is that the js file checked on the page may load late. When it loads late, it looks like there is no cf on the page. In the code you sent, the page title comes directly, so it works smoothly. I will soon create a library that solves captchas for free. There will be a stable version in it. I am glad your problem is solved.

**Comment by EgglezosK** [comment]
Thank you for your contriebution! 

Mark it as closed!
